"""Object storage module (Cloudflare R2)."""
from .r2 import (
    R2NotConfigured,
    get_client,
    is_configured,
    bucket_name,
    put_object,
    get_object_stream,
    object_exists,
    delete_object,
    put_bucket_cors,
    get_bucket_cors,
    presigned_put_url,
    presigned_get_url,
    video_key,
    pose_csv_key,
    export_key,
)

__all__ = [
    'R2NotConfigured',
    'get_client',
    'is_configured',
    'bucket_name',
    'put_object',
    'get_object_stream',
    'object_exists',
    'delete_object',
    'put_bucket_cors',
    'get_bucket_cors',
    'presigned_put_url',
    'presigned_get_url',
    'video_key',
    'pose_csv_key',
    'export_key',
]
